server:
  port: 9002
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 121.40.105.242:8848 #注册中心地址
    gateway:
      routes:
        - id: provider-route
          uri: lb://provider
          predicates:
            - Path=/provider/**
          filters:
            - StripPrefix=1
        - id: consumer-route
          url: lb://consumer
          predicates:
            - Path=/consumer/**
          filters:
            - StripPrefix=1